[workspace]
authors = ["Andrew <andrewgsavage@gmail.com>"]
channels = ["conda-forge"]
name = "ansys_notes"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]
build = {cmd = "sphinx-build -M html source build", cwd ="docs"}

[dependencies]
sphinx = ">=8.2.3,<9"
